### ISSUE TITLE
all files are called “template.xlsx”

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-ui#72]
Currently, all files downloaded from the deposition app are called “template.xlsx” - this includes three different types of file: 1) the basic empty template downloaded from the “DOWNLOAD TEMPLATE” button in the top toolbar, 2) the pre-filled summary statistics template downloaded from the “DOWNLOAD SS TEMPLATE” button within a submission, 3) the user’s completed and uploaded template downloaded from the “DOWNLOAD DATA FILE” button within a submission. I found it confusing to keep track of these different files, which all had the same name - ES

The download template file name is currently “template.xlsx” by default from Template Service app, let me check where the other file names are being set… - TW

**Comment by twhetzel** [comment]
From ES:
OK, my suggestion is that we call the basic empty template (1) "new_template.xlsx", the pre-filled template for adding sum stats URLs (2) "prefilled_template.xlsx", and the user's completed template (3) "uploaded_template.xlsx". But please discuss other names if anyone thinks of something better.

It would be nice to also append the PMID or some other specific identifier at the end to distinguish each individual spreadsheet (only for type 2 and 3 in the above comment), but that could be a later step.

**Comment by twhetzel** [comment]
- Updated the file name to "new_template.xlsx" for the basic empty Metadata template downloaded from the app menu bar from "Download Template"

- Updated the Summary stats prefilled template to "prefilled_template_PMID.xlsx", where PMID is the actual PubmedId for the publication. This file is from the "Download SS Template" button.

- The filename for the "Download Data File" was not changed since the filename here is what the user named the file they uploaded as the data file.
